-- Auto-generated by scripts/parse-vercel-schedule-log.mjs
-- Source: my-attendance-log-export-2026-04-08T02-54-51.json (14 days; only 2 rows recoverable from logs)
BEGIN;

UPDATE public.shifts SET start_planned = '09:00', end_planned = '18:00', start_planned2 = NULL, end_planned2 = NULL WHERE user_id = '77f99b3a-b96a-4945-8670-1510d143d803'::uuid AND date = '2026-04-08'::date AND TRIM(start_planned) IN ('なし', '') AND TRIM(end_planned) IN ('なし', '');
INSERT INTO public.shifts (id, user_id, date, start_planned, end_planned, start_planned2, end_planned2) SELECT gen_random_uuid(), '77f99b3a-b96a-4945-8670-1510d143d803'::uuid, '2026-04-08'::date, '09:00', '18:00', NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM public.shifts s WHERE s.user_id = '77f99b3a-b96a-4945-8670-1510d143d803'::uuid AND s.date = '2026-04-08'::date);

UPDATE public.shifts SET start_planned = '10:00', end_planned = '12:00', start_planned2 = NULL, end_planned2 = NULL WHERE user_id = 'bfa42f7a-fd2a-47de-91ca-50735df7b966'::uuid AND date = '2026-04-13'::date AND TRIM(start_planned) IN ('なし', '') AND TRIM(end_planned) IN ('なし', '');
INSERT INTO public.shifts (id, user_id, date, start_planned, end_planned, start_planned2, end_planned2) SELECT gen_random_uuid(), 'bfa42f7a-fd2a-47de-91ca-50735df7b966'::uuid, '2026-04-13'::date, '10:00', '12:00', NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM public.shifts s WHERE s.user_id = 'bfa42f7a-fd2a-47de-91ca-50735df7b966'::uuid AND s.date = '2026-04-13'::date);

COMMIT;
